#pragma once

#include <string>

namespace gwbasic {

enum class TokenType {
    EndOfLine,
    Number,
    String,
    Identifier,
    LineNumber,
    Comma,
    Colon,
    Semicolon,
    LeftParen,
    RightParen,
    Plus,
    Minus,
    Star,
    Slash,
    Hash,
    Equal,
    NotEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    KeywordPrint,
    KeywordUsing,
    KeywordOpen,
    KeywordClose,
    KeywordWrite,
    KeywordLine,
    KeywordAs,
    KeywordInputFile,
    KeywordOutput,
    KeywordAppend,
    KeywordRandom,
    KeywordLen,
    KeywordLet,
    KeywordInput,
    KeywordIf,
    KeywordThen,
    KeywordElse,
    KeywordAnd,
    KeywordOr,
    KeywordNot,
    KeywordGoto,
    KeywordGosub,
    KeywordReturn,
    KeywordFor,
    KeywordTo,
    KeywordStep,
    KeywordNext,
    KeywordData,
    KeywordRead,
    KeywordRestore,
    KeywordDim,
    KeywordWhile,
    KeywordWend,
    KeywordOn,
    KeywordDefint,
    KeywordDefstr,
    KeywordDefsng,
    KeywordDefdbl,
    KeywordStop,
    KeywordCont,
    KeywordEnd,
    KeywordRem,
    KeywordList,
    KeywordRun,
    KeywordNew,
    KeywordClear,
    KeywordField,
    KeywordGet,
    KeywordPut,
    KeywordLset,
    KeywordRset,
    KeywordKill,
    KeywordName,
    KeywordMkdir,
    KeywordRmdir,
    KeywordCls,
    KeywordLocate,
    KeywordColor,
    KeywordBeep,
    KeywordScreen,
    KeywordKey,
    KeywordSound,
    KeywordPlay,
    KeywordPset,
    KeywordCircle,
    KeywordPaint,
    KeywordDraw,
    KeywordView,
    KeywordWindow,
    KeywordPalette
};

struct Token {
    TokenType type{};
    std::string lexeme{};
    std::size_t column{};
};

[[nodiscard]] auto to_string(TokenType type) -> std::string;

} // namespace gwbasic
