#pragma once

#include <string>

namespace gwbasic {

/** Token categories emitted by Lexer and consumed by Parser. */
enum class TokenType {
    EndOfLine,
    Number,
    String,
    Identifier,
    LineNumber,
    Comma,
    Colon,
    Semicolon,
    LeftParen,
    RightParen,
    Plus,
    Minus,
    Star,
    Slash,
    Backslash,
    Caret,
    Hash,
    Equal,
    NotEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    KeywordPrint,
    KeywordUsing,
    KeywordOpen,
    KeywordClose,
    KeywordWrite,
    KeywordLine,
    KeywordAs,
    KeywordInputFile,
    KeywordOutput,
    KeywordAppend,
    KeywordRandom,
    KeywordLen,
    KeywordLet,
    KeywordInput,
    KeywordIf,
    KeywordThen,
    KeywordElse,
    KeywordAnd,
    KeywordOr,
    KeywordMod,
    KeywordNot,
    KeywordGoto,
    KeywordGosub,
    KeywordReturn,
    KeywordFor,
    KeywordTo,
    KeywordStep,
    KeywordNext,
    KeywordData,
    KeywordRead,
    KeywordRestore,
    KeywordDim,
    KeywordErase,
    KeywordOption,
    KeywordBase,
    KeywordWhile,
    KeywordWend,
    KeywordOn,
    KeywordError,
    KeywordResume,
    KeywordDef,
    KeywordDefint,
    KeywordDefstr,
    KeywordDefsng,
    KeywordDefdbl,
    KeywordStop,
    KeywordCont,
    KeywordEnd,
    KeywordRem,
    KeywordList,
    KeywordRun,
    KeywordLoad,
    KeywordSave,
    KeywordNew,
    KeywordClear,
    KeywordField,
    KeywordFiles,
    KeywordGet,
    KeywordPut,
    KeywordLset,
    KeywordRset,
    KeywordSwap,
    KeywordKill,
    KeywordName,
    KeywordMkdir,
    KeywordChdir,
    KeywordRmdir,
    KeywordCls,
    KeywordLocate,
    KeywordWidth,
    KeywordColor,
    KeywordBeep,
    KeywordScreen,
    KeywordKey,
    KeywordPoke,
    KeywordSound,
    KeywordPlay,
    KeywordRandomize,
    KeywordPset,
    KeywordCircle,
    KeywordPaint,
    KeywordDraw,
    KeywordView,
    KeywordWindow,
    KeywordPalette
};

/** One lexical token with its original lexeme and 1-based source column. */
struct Token {
    TokenType type{};
    std::string lexeme{};
    std::size_t column{};
};

/** Return a human-readable token name, mostly for diagnostics and tests. */
[[nodiscard]] auto to_string(TokenType type) -> std::string;

} // namespace gwbasic
